version: "3.9"
services:

  database:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: meu_pet_db
    # volumes:
    #   - mysql:/usr/local/var/mysql

  server:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - database
volumes:
  mysql: